### ISSUE TITLE
Webpack 4 support

### ISSUE THREAD

**Issue by esbenp** [SimenB/add-asset-html-webpack-plugin#97]
Hi, has this plugin been updated for webpack 4? I am trying to get it work but I get the following error

```
TypeError: callback is not a function
    at /Users/xxx/node_modules/add-asset-html-webpack-plugin/lib/addAllAssetsToCompilation.js:110:7
    at Generator.next (<anonymous>)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at exports.default (/Users/xxx/node_modules/add-asset-html-webpack-plugin/lib/addAllAssetsToCompilation.js:112:57)
    at compilation.plugin (/Users/xxx/node_modules/add-asset-html-webpack-plugin/lib/index.js:14:87)
    at Promise (eval at create (/Users/xxx/node_modules/tapable/lib/HookCodeFactory.js:51:12), <anonymous>:11:16)
    at new Promise (<anonymous>)
    at AsyncSeriesWaterfallHook.eval [as promise] (eval at create (/Users/xxx/node_modules/tapable/lib/HookCodeFactory.js:51:12), <anonymous>:4:8)
    at AsyncSeriesWaterfallHook.lazyCompileHook [as _promise] (/Users/xxx/node_modules/tapable/lib/Hook.js:35:21)
    at /Users/xxx/node_modules/html-webpack-plugin/index.js:643:47
    at Promise.resolve.then.then.then.then.compilationResult (/Users/xxx/node_modules/html-webpack-plugin/index.js:160:36)
    at <anonymous>
```

my config is something along the lines of

```
if (dllPlugin) {
  glob.sync(`${dllPlugin.path}/*.dll.js`).forEach((dllPath) => {
    plugins.push(
      new AddAssetHtmlPlugin({
        filepath: dllPath,
        includeSourcemap: false,
      })
    );
  });
}
```

path to dll seems to be correct

**Comment by SimenB** [comment]
I haven't done anything to update.

PR very much welcome 🙂

**Comment by asadsahi** [comment]
Blocker for me as well to upgrade to webpack 4. Exact error while trying to upgrade my project which is react-boilerplate based.

**Comment by SimenB** [comment]
I've published `add-asset-html-webpack-plugin@next` which should support Webpack 4. At least the example in this repo looks correct! 🙂 Would love help testing it

Opened up #99 for stable release.

**Comment by SimenB** [comment]
Actually no real reason for me to not release a small patch without a major, so I'll do that. Will still be a major coming though, as the new code is a bit simpler

**Comment by esbenp** [comment]
Cheers @SimenB ! Much appreciated :-)

**Comment by SimenB** [comment]
@esbenp BTW, the plugin supports globs, syou you should be able to set your config to this:

```js
new AddAssetHtmlPlugin({
    filepath: `${dllPlugin.path}/*.dll.js`,
    includeSourcemap: false,
  })
```
